version: '3.9'
blog-database:
    image: mongo
    ports:
        - '27017:27017'
blog-backend:
    build: backend/
    environment:
        - PORT=3001
        - DATABASE_URL=mongodb://host.docker.internal:27017/blog
    ports:
        - '3001:3001'
    depends-on:
        - blog-database
blog-frontend:
    build:
        context: .
        args: VITE_BACKEND_URL:http://localhost:3001/api/v1
    ports:
        - '30000:80'
    depends-on:
        - blog-backend
